kubernetes-intro:
  - changed-files:
      - any-glob-to-any-file: kubernetes-intro/**

kubernetes-controllers:
  - changed-files:
      - any-glob-to-any-file: kubernetes-controllers/**

kubernetes-security:
  - changed-files:
      - any-glob-to-any-file: kubernetes-security/**

kubernetes-debug:
  - changed-files:
      - any-glob-to-any-file: kubernetes-debug/**

kubernetes-gitops:
  - changed-files:
      - any-glob-to-any-file: kubernetes-gitops/**

kubernetes-logging:
  - changed-files:
      - any-glob-to-any-file: kubernetes-logging/**

kubernetes-monitoring:
  - changed-files:
      - any-glob-to-any-file: kubernetes-monitoring/**

kubernetes-networks:
  - changed-files:
      - any-glob-to-any-file: kubernetes-networks/**

kubernetes-operators:
  - changed-files:
      - any-glob-to-any-file: kubernetes-operators/**
  
kubernetes-production-clusters:
  - changed-files:
      - any-glob-to-any-file: kubernetes-production-clusters/**

kubernetes-storage:
  - changed-files:
      - any-glob-to-any-file: kubernetes-storage/**

kubernetes-templating:
  - changed-files:
      - any-glob-to-any-file: kubernetes-templating/**

kubernetes-vault:
  - changed-files:
      - any-glob-to-any-file: kubernetes-vault/**

kubernetes-volumes:
  - changed-files:
      - any-glob-to-any-file: kubernetes-volumes/**
  
Review Required:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes-templating/**
          - kubernetes-production-clusters/**
          - kubernetes-monitoring/**
          - kubernetes-logging/**
          - kubernetes-debug/**

# --- Метки по конкретным типам манифестов ---

namespace:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes-intro/namespace.yaml
          - kubernetes-controllers/namespace.yaml

pod:
  - changed-files:
      - any-glob-to-any-file: kubernetes-intro/pod.yaml

deployment:
  - changed-files:
      - any-glob-to-any-file: kubernetes-controllers/deployment.yaml
