apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework

spec:
  initContainers:
    - name: init-container
      image: busybox:1.37
      command:
        - sh
        - -c
        - |
          wget -O /init/index.html https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
      volumeMounts:
        - name: homework-volume
          mountPath: /init

  containers:
    - name: web
      image: busybox:1.37
      command:
        - sh
        - -c
        - |
          httpd -f -p 8000 -h /homework
      ports:
        - containerPort: 8000

      volumeMounts:
        - name: homework-volume
          mountPath: /homework

      lifecycle:
        preStop:
          exec:
            command:
              - sh
              - -c
              - rm -f /homework/index.html

  volumes:
    - name: homework-volume
      emptyDir: {}
